<div style="background: linear-gradient(135deg, #1e293b 0%, #0f172a 100%); padding: 30px; border-radius: 8px; margin-bottom: 25px; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);">
    <h1 style="color: #f8fafc; font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; font-weight: 700; margin: 0; font-size: 2.2em; letter-spacing: -0.5px;"> Unificacion datos globales PISA-OECD 🌍
</h1>
    <p style="color: #94a3b8; font-family: 'Segoe UI', sans-serif; margin: 8px 0 0 0; font-size: 1.1em;">Generacion de los datos finales para su estudio </p>
    
</div>

In [1]:
import pandas as pd
import os

In [26]:
ruta_datos_intermedios ='../../data/intermediate'
ruta_datos_procesados ='../../data/processed'

Se debe realizar la lectura de los dataFrames que contienen los datos de los resultados de matemáticas medis por pais de los informes PISA y los datos de los indices derivados medios de cada pais

In [3]:
ruta_datos_matematicas = os.path.join(
    ruta_datos_intermedios,
    'pisa22_math_pais_consolidado.parquet'
    )

ruta_datos_indices_pais = os.path.join(
    ruta_datos_intermedios,
    'pisa22_submuestra_paises.parquet'
    )

In [4]:
#Lectura de las medias de matemáticas por paises
df_resultados_matematicas = pd.read_parquet(ruta_datos_matematicas)

#Lectura de las medias de los indices derivados por paises
df_indices_paises = pd.read_parquet(ruta_datos_indices_pais).reset_index()

In [5]:
df_resultados_matematicas.head()

   CNT  media_math_pisa  varianza_imputacion
0  ALB       368.221720             0.369265
1  ARE       431.110477             0.127318
2  ARG       377.529029             0.174689
3  AUS       487.084254             0.120797
4  AUT       487.267499             0.171985

In [6]:
df_indices_paises.head()

,CNT,PAREDINT,HISEI,HOMEPOS,ESCS,BELONG,TEACHSUP,MATHEFF,ANXMAT,STRATIO,PROPMATH,STAFFSHORT,EDUSHORT
0,ALB,12.995368,45.751011,-0.839871,-0.708247,0.122006,0.308400,-0.367129,0.139956,13.937516,0.111787,-0.655399,0.098963
1,ARE,15.057775,65.236542,-0.200819,0.279370,-0.224651,0.174018,-0.290678,0.182672,14.438646,0.147710,0.066412,-0.278198
2,ARG,12.906470,43.960266,-0.874134,-0.771609,-0.199733,0.258542,-0.724162,0.439967,9.147843,0.108352,0.514345,0.606678
3,AUS,14.570253,57.972633,0.422583,0.323736,-0.227144,0.123185,-0.281157,0.178700,12.847009,0.163637,0.041028,-0.667685
4,AUT,14.081729,51.757549,0.198276,0.031946,0.427076,-0.398491,0.007452,0.078246,10.350581,0.150821,-0.059988,-0.361610

Se descarla la varianza de imputacion de las medias de matematicas al no se de utilizad en el estudio final

In [20]:
df_resultados_matematicas.drop(columns='varianza_imputacion',inplace=True)

Realizamos la union de amnos dataframes por el código del pais

In [21]:
df_analisis_global = pd.merge(
    df_resultados_matematicas,
    df_indices_paises,
    on='CNT',
    how='right'    
)

In [22]:
df_analisis_global.head()

,CNT,media_math_pisa,PAREDINT,HISEI,HOMEPOS,ESCS,BELONG,TEACHSUP,MATHEFF,ANXMAT,STRATIO,PROPMATH,STAFFSHORT,EDUSHORT
0,ALB,368.221720,12.995368,45.751011,-0.839871,-0.708247,0.122006,0.308400,-0.367129,0.139956,13.937516,0.111787,-0.655399,0.098963
1,ARE,431.110477,15.057775,65.236542,-0.200819,0.279370,-0.224651,0.174018,-0.290678,0.182672,14.438646,0.147710,0.066412,-0.278198
2,ARG,377.529029,12.906470,43.960266,-0.874134,-0.771609,-0.199733,0.258542,-0.724162,0.439967,9.147843,0.108352,0.514345,0.606678
3,AUS,487.084254,14.570253,57.972633,0.422583,0.323736,-0.227144,0.123185,-0.281157,0.178700,12.847009,0.163637,0.041028,-0.667685
4,AUT,487.267499,14.081729,51.757549,0.198276,0.031946,0.427076,-0.398491,0.007452,0.078246,10.350581,0.150821,-0.059988,-0.361610

In [27]:
parquet_submuestra_pais_consolidada=os.path.join(ruta_datos_procesados,'pisa22_submuestra_pais_consolidada.parquet')

In [28]:
df_analisis_global.to_parquet(parquet_submuestra_pais_consolidada)